Microsoft/napajs

.npmignore, .travis.yml, README.md, appveyor.yml, package.json
- Use a fully customized matrix on travis
- Fix CMake missing on ubuntu precise
- Add AppVeyor support
=> Update CI build matrix for travis and appveyor

docs/api/transport.md, docs/api/zone.md, lib/index.ts, lib/transport/function-transporter.ts, lib/v8.ts, lib/v8/stack-trace.ts, lib/zone/function-call.ts, lib/zone/zone-impl.ts, src/module/loader/binary-module-loader.cpp, src/module/loader/binary-module-loader.h, src/module/loader/core-module-loader.cpp, src/module/loader/core-module-loader.h, src/module/loader/javascript-module-loader.cpp, src/module/loader/javascript-module-loader.h, src/module/loader/json-module-loader.cpp, src/module/loader/json-module-loader.h, src/module/loader/module-file-loader.h, src/module/loader/module-loader.cpp, src/module/loader/module-resolver.cpp, src/module/loader/module-resolver.h, test/memory-test.ts, test/module-test.ts, test/module/resolution-tests.js, test/store-test.ts, test/transport-test.ts, test/zone-test.ts
This change addresses [issue](https://github.com/Microsoft/napajs/issues/30) to make `zone.execute` on anonymous function more fluent. Also it made transported functions more secure, which can only access their own v8 contexts.
1) Support `require(path, script)` to create module from string in Napa zone.
2) Introduce `napa.v8.currentStack` to get current stack.
3) Replace `eval` with creating a new module for transported function.
4) Use caller JS file + function hash as module id for transported function. As a result, transported function will use __dirname from caller.
5) Updated test files.
We always assume that the function passed to `zone.execute` without property `origin` is to use caller file as origin. This assumption makes most fluent usage for most cases, but if functions are …
=> Polish zone.execute: transported function will inherit __dirname from caller.

.npmignore
remove third-party dir in npmignore for building during npm install when pre-build retriving failed
=> remove third-party dir in npmignore

.travis.yml
Fix compiler name in OS X. (AppleClang version is not LLVM version)
=> Update comments in .travis.yml

scripts/install.js
Add a new commandline option '--no-prepare' to disable the force prepare in the install.js
=> Allow to skip force prepare in installation process

src/module/loader/module-loader-helpers.cpp
This switch is defined and set to true, when running Napa in embed mode.
=> Export '__in_embed' switch

examples/tutorial/estimate-pi-in-parallel/estimate-pi-in-parallel.js
```js
.then(b => run().then(...))
```
equals to
```js
.then(b => run()).then(...)
```
No nesting required :)
=> Unnest promises in pi example

node/CMakeLists.txt
This change should resolve issue #80 .
- Update rpath to '$ORIGIN/' on Linux.
- Update rpath to '@loader_path' on Mac OS.
=> Fix RPATH for shared library

docs/api/zone.md
While reading through the Zone API documentation I found a few small grammar issues in the introduction that slowed down my understanding. I went ahead and did a quick pass for grammar on the rest of the page as well.
=> Update Zone API Documentation Grammar

inc/napa/capi.h, inc/napa/zone.h, src/api/capi.cpp, src/settings/settings-parser.h, unittest/settings/parser-tests.cpp
**This change has modification on napa's C API.**
=> Fix build warning: ISO C++ forbids converting a string constant to ‘char*’

.travis.yml, appveyor.yml
Since Node.js released v9.0.0 and shifted LTS from 6.x to 8.x, we should update our CI matrix Node.js version from [4,6,8] to [6,8,9].
=> Update CI matrix for Node.js versions

.travis.yml, appveyor.yml, lib/binding.js
* For node <4.5 and >=8.5.0 (https://github.com/Microsoft/napajs/issues/96) Napa.js is not running.
* The previous behavior uses process.exit() to quit the running process. This will break some automation scripts that depends on error code. Now an exception will be thrown.
* CI matrix also updated to ignore errors on node v9.x
=> Throw exception when node version is not supported

unittest/zone/timer-tests.cpp
* There is a separated open issue (label:optimization) https://github.com/Microsoft/napajs/issues/33 for making the timer more precise.
* This change is to fix the unittest random failure that caused by timer.
=> Add the timer timeout resolution to 100ms in unittest

src/platform/dll.cpp
This is a workaround to fix inconsistency of __dirname and __filename between Napa.js and Node.js.
The root cause is, Napajs does not fully support Windows UNC prefix yet. #131 is created to track
this issue.
=> dll::ThisLineLocation(): Remove UNC prefix '\\?\' if it presents

.travis.yml, appveyor.yml
Previous change https://github.com/Microsoft/napajs/commit/848b3713b1cb9ab67e26760f632b9db358436192 fails Napa.js on Node > 8.4.0 due to issue https://github.com/Microsoft/napajs/issues/96, so we also updated the corresponding Node version in CI matrix:
- Node 8.x: Fixed to 8.4.0
- Node 9.x: Current (Latest Release), Allow failure
Now we have a workaround in https://github.com/Microsoft/napajs/commit/0a22b5725d8156ce584e141e585ed956ed86eeb7 and it's time to revert the CI matrix:
- Node 8.x: LTS (Latest Release)
- Node 9.0: Current (Latest Release)
=> [CI matrix] Revert node version for LTS/current to latest

lib/zone/zone-impl.ts, test/memory-test.ts, test/module-test.ts, test/store-test.ts, test/zone-test.ts
This change apply @tswaters 's patch on APIs that needs to be called back to Node event loop.
The issue was discussed in [https://github.com/audreyt/node-webworker-threads/issues/123#issuecomment-254019552](https://github.com/audreyt/node-webworker-threads/issues/123#issuecomment-254019552)
Verified this change fixes #27, #32, and #139.
=> Fix hanging promise when callback from Napa to Node

src/module/core-modules/napa/lock-wrap.cpp
Add a `static_cast` to fix the following build warning:
`conversion from 'size_t' to 'int', possible loss of data`
=> Fix a build warning in lock-wrap.cpp

inc/napa/log.h
Fix fix macro `LOG` when `NAPA_LOG_DISABLED` is set.
- `UNUSED(arg)` will fail if `arg` is empty.
- The previous implementation expended to multiple statements, which may cause issue
=> fix macro LOG when NAPA_LOG_DISABLED is set

.travis.yml
To unblock CI build from https://github.com/Microsoft/napajs/issues/162, I am doing this temporary change.
=> Fix Node's version to 9.2.1 on CI build (Linux)

docs/api/zone.md
I recognize this is small, it just caught my eye while reading this said "Augular" instead of "Angular" 😄
=> Fixes Angular typo

lib/core/.gitignore, lib/core/.npmignore
Both javascript and typescript files should be supported in folder /lib/core.
This is because sometimes we borrow javascript code from Node.js implementation, and sometimes we have our own typescript implementation.
=> Allow both .js and .ts files in /lib/core

lib/binding.js, package.json
This fixes the bug in node version check in file `lib/binding.js`
The behavior is to perform version check as string comparison, which causes `'v8.10.0' < 'v8.4.0' === true`.
fixes #200
=> Fix node version check

src/utils/debug.h
The macro `NAPA_DEBUG` should be ignored completely when `DEBUG_NAPA` is not set.
[example] considering this code snippet:
```cpp
NAPA_DEBUG("test", "this is a string: %s", calculate_a_string(args).c_str());
```
Function `calculate_a_string` should not be called when `DEBUG_NAPA` is not set.
=> Optimize macro napa debug

third-party/args/LICENSE, third-party/args/args.hxx
Update to https://github.com/Taywee/args/commit/7bf17000aa0969b8ca3178c72ec834b105944a41.
The old version uses `dynamic_cast`, which requires RTTI enabled.
New version removed the usage.
=> Update 3rd party library 'args' to latest version (7bf1700)

src/platform/process.cpp
Add the missing header file <functional> which causes build break on g++7.x
Fix #220
=> Fix build: add missing header file

inc/napa/v8-helpers/json.h, src/module/core-modules/napa/lock-wrap.cpp, src/module/loader/javascript-module-loader.cpp, test/transport-test.ts
1.disable test cases of builtin-type-transportation; 2.fix build break
=> fix build/test break introduced by v8 breaking change from node v10.x

.travis.yml, CMakeLists.txt, appveyor.yml
Update linker flags to prevent resolving incorrect symbols.
Fixes https://github.com/Microsoft/napajs/issues/162 and https://github.com/Microsoft/napajs/issues/225.
=> Fix crash on some linux environment

src/module/loader/javascript-module-loader.cpp
In the top-level code in a Node module, `this` is equivalent to `module.exports`. Some packages uses `this.some_func = xxx` instead of `module.exports.some_func = xxx`, which is not working in current Napa.js worker.
This is supposed to fix #231.
=> Set 'this' reference to module.exports in module's top level code

src/zone/worker.cpp
node doesn't need this flag since v10.2.0. Please refer to [20719](https://github.com/nodejs/node/pull/20719)
=> remove --allow-native-syntax flag during worker initialization

inc/napa/exports.h, inc/napa/module/binding.h, src/store/store.h, src/v8-extensions/v8-extensions.h, src/zone/node-zone.h, src/zone/worker-context.h
This change removed macro `NAPA_BINDING_API` since it is no longer useful in v0.4.x.
Some unnecessary declarations of macro `NAPA_API` are also removed.
=> clean macro NAPA_API and NAPA_BINDING_API

package.json
Hi Napajs team, 
I was installing Napajs from master and it failed as a result of a missing dependency, cmake-js. I've added it to the package.json, although I just put the most recent version; what would be the most appropriate minimum version requirement?
-Daniel
=> Add cmake-js dependency to package.json

benchmark/README.md, docs/api/module.md, docs/api/store.md, examples/modules/plus-number/README.md, examples/tutorial/napa-runner/README.md, scripts/embedded.js
This PR fixes some small typos in the documentation and one in the code.
=> Fix some small typos

docs/api/module.md, docs/api/zone.md
Fixed minor typos in docs! :smile:
=> fixed typos
